# Generated by Django 3.2.8 on 2021-11-02 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Predonation',
            fields=[
                ('Pre_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('address', models.CharField(max_length=250)),
                ('phone', models.IntegerField()),
                ('city', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=250)),
                ('amount', models.IntegerField()),
                ('check', models.CharField(max_length=250)),
            ],
        ),
    ]
