# Generated by Django 3.2.8 on 2021-11-02 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('helpapp', '0002_predonation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('D_id', models.AutoField(primary_key=True, serialize=False)),
                ('cardno', models.IntegerField()),
                ('expdate', models.DateField()),
                ('cvv', models.IntegerField()),
                ('chname', models.CharField(max_length=250)),
                ('ch_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helpapp.predonation')),
            ],
        ),
    ]
